### ISSUE TITLE
Plugin doesn't compile with Qt Creator 3.3.0

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dlangeditor#5]
Some internals seem to have changed using the latest QTC version:

In file included from dlangeditorplugin.cpp:4:0:
dlangeditor.h:4:41: fatal error: texteditor/basetextdocument.h: No such file or directory
 #include <texteditor/basetextdocument.h>
