### ISSUE TITLE
Compile with QtCreator 3.5

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dlangeditor#15]
I'm getting the following error when trying to compile with QtC 3.5:

```
src/dlangoutlinemodel.cpp: In member function 'virtual QStringList DlangEditor::DlangOutlineModel::mimeTypes() const':
src/dlangoutlinemodel.cpp:152:19: error: 'Utils::FileDropSupport' has not been declared
src/dlangoutlinemodel.cpp: In member function 'virtual QMimeData* DlangEditor::DlangOutlineModel::mimeData(const QModelIndexList&) const':
src/dlangoutlinemodel.cpp:157:32: error: 'FileDropMimeData' in namespace 'Utils' does not name a type
```
