### ISSUE TITLE
Plugin doesn't compile with Qt Creator 3.3.81 (QtC 3.4 beta 1)

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dlangeditor#11]
Trying out the fresh new beta 1 I'm getting the following error:

```
src/dlangeditorplugin.cpp:24:37: fatal error: coreplugin/mimedatabase.h: No such file or directory
 #include <coreplugin/mimedatabase.h>
```

This one is easy to fix but after that I'm getting:
```
src/dlangeditorplugin.cpp:24:37: fatal error: coreplugin/mimedatabase.h: No such file or directory
 #include <coreplugin/mimedatabase.h>
```

.. and then I gave up for now :-) Seems that QtC has undergone again some refactorings since the last release.
